name: CI

on: pull_request, push

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: install pylint 2.4.4
        run: |
          python -m pip install --upgrade pip
          pip install pylint=2.4.4

      - name: fetch main for diff
        run: git fetch origin main:main

      - name: run pylint script
        run: bash ./.github/scripts/pylint.sh --incremental